.github/CONTRIBUTING.md, CONTRIBUTING.md
Merges the two `contributing` guideline docs into one, minor updates.
=> docs: unify contributing guidelines

.eslintrc
Updates `eslint` rules to `es6` as we are nodejs4 compatible
=> chore: eslint es6 update

.travis.yml
Update tests to verify against different java versions: 8, 9 & 11
=> feat: Update test matrix

package.json
=> fix: update lodash to v4.17.15

.travis.yml
Added support for jdk10 and jdk11
#31
=> feat: Add support for jdk10 and jdk11

README.md
Clarifies intended use of plugin.
=> docs: Clarify intended use

README.md
Adds the Snyk badge to the read me.
At the beginning.
=> docs: adds Snyk badge to Readme

lib/pom.ts, test/fixtures/my-app/pom.xml, test/fixtures/snyk/pom.xml, test/functional/pom.test.ts
Added createPom function.
Added tests and fixtures.
BST-1047
=> feat: add function to create pom.xml

README.md
Update docs to document our support
=> Update docs with Supported Java & mvn versions

package.json
=> feat: drop unused lodash

package.json
Use patched java graph builder
=> feat: use latest java graph builder with patched lodash

README.md
=> chore: update readme to fix a type Gradle -> Maven

package.json
bump java call graph builder to include support up to java 13
=> feat: bump java call graph builder to include support up to java 13

lib/error-format.ts, tests/functional/error-format.test.ts
A change was made in the upstream to the error message,
this change will align the two.
=> fix: correct error message for no target folder

package.json
Bump call graph generator dependency to pick up timeout clearing fix.
=> fix: use the call graph generator with the clear timeout fix

package.json
Switch to dirs as entrypoints when creating a call graph
https://snyksec.atlassian.net/browse/FLOW-330
=> feat: switch to dirs as entrypoints when creating a call graph

package.json
In order to prevent too long command, transfer classpath through a file in a new version of java-call-graph-builder
Linking snyk-mvn-plugin to your local installation of snyk and running snyk test/monitor command with --reachable
https://github.com/snyk/java-call-graph-builder/pull/25
https://github.com/snyk/java-call-graph-generator/pull/24
=> fix: transfer classpath via file

package.json
Propagates forgotten promise race condition fix from https://github.com/snyk/java-call-graph-builder/pull/26
=> fix: forgotten promise race condition

package.json, tests/system/plugin-reachable-vulns.test.ts
Upgrades cli-interface and java-call-graph-builder to latest upstream version.
HAMMER-99
=> fix: update cli-interface and java-call-graph-builder to latest

lib/index.ts
=> fix: support allProjects only in scanAllUnmanaged flag

package.json
do not display logs while downloading the call graph generator
https://snyksec.atlassian.net/browse/FLOW-437
=> feat: do not display logs while downloading the call graphs

package.json
bump java call graph builder to fix windows issue
More info at:
https://github.com/snyk/java-call-graph-builder/pull/36
https://snyksec.atlassian.net/browse/FLOW-406
=> feat: bump java call graph builder to fix windows issue

package.json
Uses the java call graph builder with improved logic. Details: https://github.com/snyk/java-call-graph-builder/pull/41.
=> feat: use call graph builder with improved logic

lib/sub-process.ts
If available restore system proxy settings before launching a subprocess. Similar to other plugins.
=> fix: restore system proxy

.circleci/config.yml, lib/index.ts
Fixes:
- choco times out because of the missing -y flag
- small ts issue
=> fix: fixed ts issue

lib/index.ts, tests/jest/system/dverbose-flag.spec.ts, tests/tap/system/plugin.test.ts
1. Reverts the following changes -> https://github.com/snyk/snyk-mvn-plugin/pull/171
2. Increases the timeout time for a dverbose test
=> fix: revert dverbose v3.4.0

.circleci/config.yml, lib/error-format.ts, lib/maven/dependency-resolve.ts, lib/maven/dependency-tree.ts, package.json, tests/fixtures/bad with spaces/pom.xml, tests/fixtures/maven4-aggregate/expected-dep-graph.json, tests/fixtures/maven4-aggregate/maven4-service/expected-dep-graph.json, tests/fixtures/maven4-aggregate/maven4-service/pom.xml, tests/fixtures/maven4-aggregate/maven4-web/pom.xml, tests/fixtures/maven4-aggregate/pom.xml, tests/fixtures/maven4-basic/expected-dep-graph.json, tests/fixtures/maven4-basic/pom.xml, tests/jest/functional/maven/dependency-resolve.spec.ts, tests/jest/functional/maven/dependency-tree.spec.ts, tests/jest/system/maven4.spec.ts, tests/jest/system/plugin.spec.ts
This adds the Maven 4 release candidate to the CICD pipeline as well as adding some basic fixtures for maven 4 projects. There is also a small adjustment to how we build the args when passing a file.
- [New in maven 4](https://maven.apache.org/whatsnewinmaven4.html)
=> fix: Tentative Maven4 support
