snyk/snyk-mvn-plugin

lib/index.js
test/functional/mvn-plugin.test.js

Double-dash arguments are now sent as an array of strings, split by spaces.
Supports older, string-string arguments as well, so no breaking change here.

feat: supporting args as an array

---

lib/parse-mvn.js
test/fixtures/maven-dependency-tree-with-type.txt
test/functional/parse-mvn.test.js

when setting the type attribute in the dependency it adds another column in the dependency tree which broke our version detection

fix: improve ver detection logic in dep tree, support diff len of attr

---

lib/index.js
lib/parse-mvn.js
test/fixtures/maven-dependency-tree-error.txt
test/functional/parse-mvn.test.js
test/system/plugin.test.js

The plugin throws a `string` on parsing failures. The CLI expects an `Error` object on plugin failures. This mismatch results in obscure user output such as:
```
For path `path/to/maven/project`, undefined
- Analyzing maven dependencies for pom.xml
```
This PR changes the behaviour of the plugin to reflect this, and adds a test case with an `[ERROR]` maven output for better verbosity.

fix: throw on parsing errors, as expected by the cli

---

lib/index.js
lib/sub-process.js
test/fixtures/bad-pom.xml
test/system/plugin.test.js

When `mvn` execution ends with an error, the plugin used to reject with a string containing the stdout or stderr of the `mvn` process. This doesn't work well with the CLI, which expects proper `Error` objects on plugin failure. Now fixed!

fix: throw proper error on failing mvn execution

---

lib/parse-mvn.js
test/fixtures/maven-parse-dev-results.json
test/fixtures/maven-parse-results.json

- removes unused `groupId` and `artifactId` from response
- also removes "packaging" attribute
- the current dependency tree format is very verbose and this gives us a tiny bit more headroom for large projects

BREAKING CHANGE: drop unused groupId and artifactId attributes from response

---

lib/jar.ts
package.json

removes dependency on `request-promise-native` in favor of more lean `needle`

fix: use needle instead of request

---

lib/index.ts
lib/parse-mvn.ts
package.json
tests/fixtures/parse-mvn/maven-versions.txt
tests/functional/parse-mvn.test.ts
tests/system/plugin-jar.test.ts
tests/system/plugin.test.ts

For better analytic insight into our userbase, we'd like to have an
overview about java and maven versions used. Prereq: https://github.com/snyk/snyk-cli-interface/pull/25

feat: add java and maven version to metadata

---

lib/index.ts
package.json
tests/fixtures/bad-maven-with-mvnw/.mvn/wrapper/MavenWrapperDownloader.java
tests/fixtures/bad-maven-with-mvnw/.mvn/wrapper/maven-wrapper.properties
tests/fixtures/bad-maven-with-mvnw/mvnw
tests/fixtures/bad-maven-with-mvnw/mvnw.cmd
tests/fixtures/bad-maven-with-mvnw/pom.xml
tests/fixtures/maven-with-mvnw/.mvn/wrapper/MavenWrapperDownloader.java
tests/fixtures/maven-with-mvnw/.mvn/wrapper/maven-wrapper.properties
tests/fixtures/maven-with-mvnw/expected.json
tests/fixtures/maven-with-mvnw/mvnw
tests/fixtures/maven-with-mvnw/mvnw.cmd
tests/fixtures/maven-with-mvnw/pom.xml
tests/system/get-command.test.ts
tests/system/plugin.test.ts

implementation for https://github.com/snyk/snyk/issues/957

feat: support for maven wrapper (mvnw)

---

lib/error-format.ts
lib/errors/call-graph-error.ts
lib/errors/custom-error.ts
lib/index.ts
package.json
tests/functional/error-format.test.ts
tests/system/plugin-reachable-vulns.test.ts
tests/system/plugin.test.ts

Present more user-friendly messages for call graph errors
This relies on https://github.com/snyk/java-call-graph-builder/pull/11
Also, moved reachable vulns system tests to its own file.
https://snyksec.atlassian.net/browse/FLOW-202

feat: better call graph errors

---

package.json

Bumps java call graph builder to fix an issue with multiple nested target dirs.
https://github.com/snyk/java-call-graph-builder/pull/17

fix: bump java-call-graph-builder to 1.8.1

---

lib/index.ts
lib/jar.ts

Enable mvn plugin to log when running the cli with `DEBUG=snyk-mvn-plugin snyk monitor --scan-all-unmanaged -d` just like we do for gradle plugin

fix: enable mvn plugging logging via cli

---

package.json

needle has a bug with sockets on newer node 12,
we're currently avoiding this newer node 12 to
evade the problem. This bug is fixed in needle
2.5.0, so let's upgrade to that.
https://github.com/tomas/needle/issues/312

feat: upgrade needle (redirect bug)

---

.circleci/config.yml

Remove `production` env var in order to install `devDeps`

fix: remove production env var

---

package.json

Upgrades the call graph builder to v1.15.1, which among other things formats messages for maven and gradle environments as well as logging parts of the stack trace of the call graph generator.

feat: upgrade call graph builder to 1.15.1

---

package.json

Updates to the new snyk-config version that should get shipped with the CLI first.
Requirement for snyk/snyk#1524
Follow up to the snyk/config#43 and snyk/java-call-graph-builder#37

fix: update java-call-graph-builder

---

package.json

Bumps the version of the java call graph builder to include the long path fix.
https://github.com/snyk/java-call-graph-builder/pull/38

fix: use Java call graph builder with long path fix

---

package.json

Use the version of the call graph builder with an added missing dependency to `tmp`.

fix: use Java call graph builder with tmp dependency

---

package.json

bumps `java-call-graph-builder` to version `1.16.5`.
The new version of java-call-graph-builder introduces better error descriptions when executing maven commands and improved newline handling for different platforms.
Running `snyk test --reachable` in windows and Linux environments

fix: better error messages and newline handling

---

lib/parse/dep-graph.ts
lib/parse/maven-graph-builder.ts
lib/parse/types.ts
tests/functional/dep-graph.test.ts
tests/functional/digraph.test.ts
tests/functional/maven-graph-builder.test.ts

This is a workaround to deal with how Maven dependency:tree outputs dependency information. Prod-like dependencies are not shown again if first seen via a test scoped dependency.
This change ensures that we keep any prod-like dependencies that are first seen through a test scope dependency.
A side-effect is that some `test` scoped dependencies will be included in the dep-graph even when `test` scoped deps are explicitly excluded.
Update: `mvn dependency:tree` does not output any `provided` or `system` transitives, so we should not do anything in that case.

feat: Keep `test` scoped deps that transitively reach prod-like deps

---

lib/parse/stdout.ts
tests/fixtures/successful-build-with-error-log/expected-dep-graph.json
tests/fixtures/successful-build-with-error-log/pom.xml
tests/functional/stdout.test.ts
tests/system/plugin.test.ts

This PR enables other plugins to log out errors without the snyk plugin throwing an error. There are cases where another plugin might log an error, but not fail the build - since some plugins might run as part of generating the dependency tree, we need to ignore those if the build overall was successful.

fix: [SUP-2210] do dot fail parsing when there is build success

---

lib/parse/dep-graph.ts
tests/tap/functional/dep-graph.test.ts

In preparation for supporting -Dverbose the breadth first search needs to retain previously visited dependency information.
At the moment we record whether a dependency has been seen (true/false) based on the maven graph node id. This id contains the dependency version. For example 'com.example:my-app:jar:jdk8:1.2.3:compile'.
However when maven is determining whether a dependency has already been seen only four properties are used:
* groupId
* artifactId
* type
* classifier (optional)
These are the properties that uniquely identify a dependency in Maven.
Changing visited to be keyed by these four properties instead.
In addition we then record the parsed dependency for these visited dependencies so that we can use that information when adding and connecting the dep-graph nodes.
The effect …

fix: record and use visited dependency information

---

lib/index.ts
lib/parse/dep-graph.ts
lib/parse/digraph.ts
lib/parse/index.ts
tests/fixtures/complex-aggregate-project/verbose-scan-result.json
tests/fixtures/test-project/expected-verbose-dep-graph.json
tests/fixtures/verbose-project/expected-verbose-dep-graph.json
tests/fixtures/verbose-project/pom.xml
tests/tap/system/plugin.test.ts
tests/tap/system/reactor.test.ts

Support passing -Dverbose to resolve omitted dependencies using maven-dependency-plugin.
When verbose is being used execute a specific version of the maven-dependency-plugin. This is becuase on lower version of this plugin outputType=dot is not supported, and it will output a tree.
When verbose is on skip pruning and ensure all dependency lines are traversed fully, using breadth first, first in wins for version resolution.

feat: support verbose

---

lib/index.ts
tests/tap/system/plugin.test.ts

Given the flag `unpruned` is passed from the CLI - we want to habdle it as if `-Dverbose` was passed as an argument to maven.
See https://github.com/snyk/cli/pull/5128

feat: support unpruned flag from CLI

---

lib/parse/dep-graph.ts
tests/fixtures/dverbose-project/expected-dverbose-dep-graph.json
tests/fixtures/dverbose-project/pom.xml
tests/jest/system/dverbose-flag.spec.ts

Cyclic dependencies were not handled until now while using the -Dverbose flag. The PR is adding support for cyclic dependencies by keeping track of the already visited packages and storing them in an ancestry list.

fix: Cyclic deps support for dverbose

---

lib/index.ts
tests/tap/system/plugin.test.ts

1. Reverts the following changes -> [link to PR](https://github.com/snyk/snyk-mvn-plugin/pull/171)
2. Switched from using lists, to using sets for dependency ancestry

Hotfix/dverbose revert v3.4.0

---

lib/index.ts
tests/jest/system/dverbose-flag.spec.ts

We need to disable the pruning to improve the results generated by `snyk sbom`.
The sbom command calls extensions with a `--print-graph` flag when it generates
an SBOM.
This PR makes use of that flag to increase the verbosity, and disabling the pruning.
- Clone snyk/snyk-mvn-plugin and snyk/cli.
- Run `npm link` in the cloned snyk-mvn-plugin directory
- If needed, run `make clean` in the cli directory
- Run `npm link snyk-mvn-plugin` in the cli directory.
- Run `make build` in the cli directory
- Create a folder with a pom.xml file, that usually gets pruned.
- Run `node <path-to-repos>/snyk/cli/dist/cli/index.js test --print-graph`
Compare the result against the same command without `--print-graph`.

feat: support --print-graph as dverbose

---

lib/parse/dep-graph.ts
lib/parse/digraph.ts
tests/fixtures/parent-node-id/expected-dverbose-dep-graph.json
tests/fixtures/parent-node-id/pom.xml
tests/jest/system/plugin-jar.spec.ts

This PR does two things:
1. We started adding the package `scope` to the identity of nodes. This fixes the `parentNodeId does not exist` issue.
2. Using the visited IDs in order to queue the correct package ID for visited nodes.

fix: [OSM-2676] dverbose - queue correct pkg id for visited node

---

lib/parse/dep-graph.ts

Had to move queue.push in the else clause. If we have `visited.id` we use that one, otherwise we use the `id`

fix: [OSM-2676] push ids from the correct clause

---

lib/parse/dep-graph.ts
tests/fixtures/test-project/expected-verbose-dep-graph.json
tests/fixtures/verbose-project/expected-verbose-dep-graph.json
tests/helpers/sort.ts
tests/jest/system/dverbose-flag.spec.ts
tests/jest/system/reactor.spec.ts
tests/tap/system/plugin.test.ts

These changes only apply for Dverbose.
1. Uses DFS for graph creation - for cycles and dense graphs.
2. Uses the package version in the key for the visited/ancestry.
Introduced a graph sort function for testing. The order of the nodes in the depGraph is changed due to the dfs change. Sorting, we can ensure the existence of the same nodes and the relationship between them. Most of the testcases keep the previous dependencies and relations.
The 2 test cases affected by the `package version in the dep key` change are the ones moved from tap tests to jest tests. Their expected graph is also updated. There are a few packages that get resolved with multiple versions by maven -Dverbose (showed as omitted). We'll keep all the versions that Dverbose outputs for now.
If it is decided to only keep …

feat: [OSM-2668] build graph for Dverbose with dfs and keep all Dverbose versions

---

lib/index.ts
lib/parse/digraph.ts
lib/parse/index.ts
tests/fixtures/dverbose-diff-scopes-versions/expected-dverbose-dep-graph-all-versions.json
tests/fixtures/test-project/expected-verbose-dep-graph-all-versions.json
tests/fixtures/verbose-project/expected-verbose-dep-graph-all-versions.json
tests/jest/system/dverbose-flag-all-versions.spec.ts

Keeps the default behaviour for dverbose to include in the dep graph only the versions of dependencies that maven resolves to - https://github.com/snyk/snyk-mvn-plugin/pull/190.
Adds an option for dverbose to include in the dep graph all the versions that maven considers for resolution - https://github.com/snyk/snyk-mvn-plugin/pull/189
Tests, see where the test outputs changed with the new option.

feat: [OSM-2667] option for dverbose to include all versions of deps considered by maven

---

lib/parse/dep-graph.ts
package.json

Quick performance improvement. `Array.shift` is `O(N)` so queue draining is currently `O(N^2)` rather than `O(N)`.
While the size of this queue should never grow too large unlike with verbose which allows node revisiting. This could still be a performance issue for very large projects
Running the local tests. Additionally you can change the `package.json` of the `cli` to point to your local repo of this. Then run `npm install && npm run build-cli:prod` to build the cli using this change. Then use the built version to test the performance on large projects
See https://github.com/snyk/snyk-gradle-plugin/issues/308 for equivalent change in gradle
We're using `@common.js/yocto-queue` instead of `yocto-queue` as the project is configured to use `commonjs` modules and moving to ES modules would …

fix: Uses an actual queue for BFS implementation
